### ISSUE TITLE
Diagrams

### ISSUE THREAD

**Issue by NorDar** [sopra-fs24-group-01/sopra-fs24-plantparent-project-management#10]
Based on the user stories from M1, create a design for the web service using component, class,
and activity diagrams with the UML standard.
- [x] sopra-fs24-group-01/sopra-fs24-plantparent-project-management#9
- [x] sopra-fs24-group-01/sopra-fs24-plantparent-project-management#8
- [x] sopra-fs24-group-01/sopra-fs24-plantparent-project-management#7
