### ISSUE TITLE
Deliverables for Milestone 2

### ISSUE THREAD

**Issue by NorDar** [sopra-fs24-group-01/sopra-fs24-plantparent-project-management#14]
- [x] Double check with M2 PDF if all tasks are fulfilled
- [x] #15
- [x] #16
- [x] Application URLs
- [x] Source Code on GitHub (#4)
- [x] #11 
- [x] Team Questions & Brownie Points (individual)
  - [x] Lazi
  - [x] Daniel
  - [x] Michael
  - [x] Nordin

**Comment by NorDar** [comment]
client url: https://sopra-fs24-group-01-client.oa.r.appspot.com/
server url: https://sopra-fs24-group-01-server.oa.r.appspot.com/

**Comment by NorDar** [comment]
URLs submitted for: GCP client|server, SonarCube, GitHub Project.

**Comment by NorDar** [comment]
Slides: https://drive.google.com/file/d/1ebQ31rWio0bsdCCh4vUP7BxFwEt8NXwq/view?usp=sharing
Report: https://drive.google.com/file/d/1xod9yVCpdRhECb5rESV3t_UPRQUiyQMa/view?usp=sharing

All staged for submission

**Comment by NorDar** [comment]
Submitted
